---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jogn.
--- DateTime: 12.10.22 16:12
---
print("------------------")

for i = 1,5 do
    toggle_pin(7, 0)
    sleep(5)
end

print("------------------")


